module.exports.Resource = {
    BLUE_OVERLAY: 'resources/groundTexture/blueOverlay.png',
    RED_OVERLAY: 'resources/groundTexture/redOverlay.png',
    GREEN_OVERLAY: 'resources/groundTexture/greenOverlay.png',
    YELLOW_OVERLAY: 'resources/groundTexture/yellowOverlay.png',
    FOG_OF_WAR: 'resources/groundTexture/fogOfWarTranslucent.png',
    DEFAULT_TILE: 'resources/groundTexture/defaultTile.png',
    BRUSH_TILE: 'resources/groundTexture/brushTile.png',
    MINERAL_TILE: 'resources/groundTexture/mineralTile.png',
    BIG_MINERAL_TILE: 'resources/groundTexture/bigMineralTile.png',
    ROCK: 'resources/groundTexture/rock.png',
    HIGH_TILE: 'resources/groundTexture/highTile.png',
    LOW_TILE: 'resources/groundTexture/lowTile.png',
    UI_TOP_RIGHT: 'resources/gui/topRight.png',
    UI_BOTTOM_LEFT: 'resources/gui/bottomLeft.png',
    UI_BOTTOM_RIGHT: 'resources/gui/bottomRight.png',
    UI_ICONS: 'resources/gui/icons.png',
    TIER_ICONS: 'resources/gui/tierIcons.png',
    CURSOR: 'resources/cursor.png',
    WIDTH_1_BUILD: 'resources/structures/width1Build.png',
    WIDTH_0_BUILD: 'resources/structures/width0Build.png',
    WIDTH_1_BUILD_ANIM: 'resources/structures/width1BuildAnimation.png',
    WIDTH_0_BUILD_ANIM: 'resources/structures/width0BuildAnimation.png',
    PROBE_ANIM: 'resources/structures/probeAnimation.png',
    ATTACK_PROJECTILE: 'resources/attack/attack.png',
    ATTACK_EXPLODING: 'resources/attack/exploding.png',
    MUZZLE_1: 'resources/muzzle/muzzle1.png',
    MUZZLE_2: 'resources/muzzle/muzzle2.png',
    MUZZLE_3: 'resources/muzzle/muzzle3.png',
    MUZZLE_4: 'resources/muzzle/muzzle4.png',
    MUZZLE_5: 'resources/muzzle/muzzle5.png',
};

module.exports.tiles = [
    module.exports.Resource.DEFAULT_TILE,
    module.exports.Resource.BRUSH_TILE,
    module.exports.Resource.MINERAL_TILE,
    module.exports.Resource.BIG_MINERAL_TILE,
    module.exports.Resource.ROCK,
    module.exports.Resource.HIGH_TILE,
    module.exports.Resource.LOW_TILE
];
